/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
//#include "finosign.h"

/* Header for class d2r_checksign_lib_FinoSign */


// ---------------------------------------------------------------------------------
// ---------------------------------------------------------------------------------
// ---------------------------------------------------------------------------------
// ---------------------------------------------------------------------------------
// ---------------------------------------------------------------------------------
// ---------------------------------------------------------------------------------
// ---------------------------------------------------------------------------------
// ---------------------------------------------------------------------------------
// ---------------------------------------------------------------------------------
// ---------------------------------------------------------------------------------

static int pen_data1[100][5000][3],pen_data2[100][5000][3],pen_data3[100][5000][3];
static unsigned char str1[50000],str2[50000];
static int len1,len2,len3,len;
static int rect_data[2][4];
static int pnum1,pnum2;

// ---------------------------------------------------------------------------------
// ---------------------------------------------------------------------------------
// ---------------------------------------------------------------------------------
// ---------------------------------------------------------------------------------
// ---------------------------------------------------------------------------------
// ---------------------------------------------------------------------------------
// ---------------------------------------------------------------------------------
// ---------------------------------------------------------------------------------
// ---------------------------------------------------------------------------------
// ---------------------------------------------------------------------------------

static int Get_Length(int data[5000][3]);
static int Merge_Data1(int data1[100][5000][3],int data2[100][5000][3],int index);
static int Merge_Data2(int data1[100][5000][3],int data2[100][5000][3],int index1,int index2);
static int Merge_Data3(int data1[100][5000][3],int data2[100][5000][3],int index1,int index2,int index3);
static int Get_Speed(int data[5000][3]);
static int Get_Speed2(int data1[5000][3],int data2[5000][3]);
static int Get_Start_Locate(int data[5000][3],int *x,int *y);
static int Get_End_Locate(int data[5000][3],int *x,int *y);
static int Check_Segment(int num,int data1[100][5000][3],int data2[100][5000][3]);
static int Get_Image_Size(int data[5000][3],int range[4]);
static int Get_Percent(unsigned char *str1,int len1,unsigned char *str2,int len2);
static int Get_Normalize(int data[100][5000][3],int rect_data[4]);
static int Get_Normalize_Part(int data[5000][3],int rect_data[4]);
static unsigned char **Get_Image(int data[100][5000][3]);
static unsigned char **Get_Image_Part(int data[5000][3],int range[4]);
static int Set_Image(unsigned char **img,int xx1,int yy1,int xx2,int yy2);
static int Get_Data(unsigned char **img,unsigned char data[1250]);
static int Get_Total_String(unsigned char *str,int data[100][5000][3]);
static int Get_Object_String(unsigned char *str,int data[100][5000][3],int index1,int index2,int num);
static int Get_Object_String_Reverse(unsigned char *str,int data[100][5000][3],int index1,int index2,int num);
static int Get_Pen_Data(unsigned char *p,int data[100][5000][3],int rect_data[4]);
static int Get_String(int x1,int y1,int x2,int y2,unsigned char *buf,int opt);
static int Get_Str(int xlen,int ylen,char c1,char c2,unsigned char *buf);
static int distance(unsigned char *string1,int len1,unsigned char *string2,int len2);


#ifndef _Included_d2r_checksign_lib_FinoSign
#define _Included_d2r_checksign_lib_FinoSign
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     d2r_checksign_lib_FinoSign
 * Method:    checkSign
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_d2r_checksign_lib_FinoSign_checkSign
  (JNIEnv* env, jclass test, jbyteArray barr1, jbyteArray barr2);

#ifdef __cplusplus
}
#endif
#endif





